### ISSUE TITLE
repo never built

### ISSUE THREAD

**Issue by jhamman** [conda-forge/intake-stac-feedstock#1]
@conda-forge-admin - this repo was setup but Azure Pipelines is showing as "Never Built"

<table><tr><td>All platforms:</td>
    <td>
      <a href="https://dev.azure.com/conda-forge/feedstock-builds/_build/latest?definitionId=8080&branchName=master">
        <img src="https://dev.azure.com/conda-forge/feedstock-builds/_apis/build/status/intake-stac-feedstock?branchName=master">
      </a>
    </td>
  </tr>
</table>

This seems like a problem with the feedstock creation. Any pointers on where to look to see what went wrong?

**Comment by ocefpaf** [comment]
Just restarted the CIs and it should be OK in a few minutes. See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=79344

PS: this is a problem we are facing with Azure lately and we are working on it. The current solution is to push an empty commit or re-start the CIs manually.

**Comment by jhamman** [comment]
Thanks @ocefpaf
