### ISSUE TITLE
incorrect sat-stac dependency

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/intake-stac-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/conda-forge/intake-stac-feedstock/blob/07f7f699037e81326ca3f50ebe376af45d9a138a/recipe/meta.yaml#L23 

is out of sync with https://github.com/intake/intake-stac/blob/main/requirements.txt#L4

figured out over in https://github.com/pangeo-data/pangeo-docker-images/pull/331

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by ocefpaf** [comment]
That is latest main. In the 0.3.0 release we have: https://github.com/intake/intake-stac/blob/c1a65ce1317d76929328fbdd554893cc10a4f6a4/requirements.txt

PR #8 corrects it for 0.3.0 release but if the code for that release is outdated we need a new one.

**Comment by scottyhq** [comment]
> That is latest main.  

🤦. Thanks for the catch @ocefpaf !
